version: "3.9"

services:

  client:
    build: ./client
    ports:
      - "1111:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "2018:5000"
    environment:
      MONGO_URI: mongodb://database:27017
    depends_on:
      - streaming
      # - broker

  streaming:
    build: ./streaming
    ports:
      - "2019:5000"
    # depends_on:
    #   - broker

  database:
    image: mongo
    volumes:
      - type: bind
        source: ./data
        target: /data/db

    ports:
      - "27017:27017"
